SELECT P.PRODUCT_CODE,(PRICE*O.TOTAL_SALES_AMOUNT) AS SALES 
FROM PRODUCT AS P 
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES_AMOUNT FROM OFFLINE_SALE 
GROUP BY PRODUCT_ID) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC,P.PRODUCT_CODE;